### ISSUE TITLE
Ethernet interface not working RPi 3

### ISSUE THREAD

**Issue by GCGarrettG** [Controlhaus/ControlPi#1]
The ethernet interface is not working on the Raspberry Pi 3.

`ip addr show` returns:
>2: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000`
`link/ether b8:27:eb:xx:xx:xx brd ff:ff:ff:ff:ff:ff

Manually setting the eth1 interface up using `ip link set dev eth1 up` resolves this but network communication still fails.

Confirmed booting board with stock Raspbian results in proper network communication.

**Comment by Controlhaus** [comment]
> ip addr show returns:
>2: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000link/ether b8:27:eb:xx:xx:xx brd ff:ff:ff:ff:ff:ff

All of my test devices show the built-in network interface as eth0.
Are you using an ethernet adapter?

Please try this image and let me know if  it works.
It has DHCP added for eth1.
https://drive.google.com/file/d/1X3Ks1RnT-P2f9jFs7Tz4z8vr9NiKEcIN/view?usp=sharing

**Comment by GCGarrettG** [comment]
Good catch.  That did the trick!  

I'm using the RPi 3's built in ethernet. 

Does your test bed include the Raspberry Pi 3?  I'll open another issue for it so this one doesn't get muddied, but it appears that the built in WiFi isn't being detected.

**Comment by Controlhaus** [comment]
Great. Will include DHCP for eth1 in the next release.
