### ISSUE TITLE
Unable to install NodeRED-plugins

### ISSUE THREAD

**Issue by MegaLionZ** [Controlhaus/ControlPi#2]
It seems so be impossible to install NodeRED-packages, although the RasPi is in rw-mode and **internet connection is verified working**. The interface of NodeRED shows the desired Plugin (omxplayer), but if I click on install, nothing happens. Also the npm package-manager via the command-line doesn't work. Is there any possibility?

**Comment by Controlhaus** [comment]
Looks like the /nodes directory is no longer used.

You can fix this by editing settings.js with:
nano  /home/pi/.node-red/settings.js

and comment out the nodes directory setting by changing:
nodesDir: '/home/pi/.node-red/nodes',

to
//nodesDir: '/home/pi/.node-red/nodes',

We'll update the next release of ControlPi too.

**Comment by Controlhaus** [comment]
Looks like npm needs to be updated with:
sudo npm i -g npm

Will get an updated image up soon...

**Comment by Controlhaus** [comment]
New image available here:
https://s3.amazonaws.com/controlpi/controlpi-1.3.1.img.zip
