### ISSUE TITLE
WiFi interface not being detected on RPi 3

### ISSUE THREAD

**Issue by GCGarrettG** [Controlhaus/ControlPi#2]
The RPi3 has built in WiFi but there is no wlanx interface shown by `ip addr show` or in `/sys/class/net`.

**Comment by Controlhaus** [comment]
That is correct. The Minibian image ControlPi is based on does not have WiFi installed.
The goal of ControlPi is to include everything you _need_ for automation and control.

I have never seen a control processor run on wifi and would not recommend it. But if there are enough requests, it will be considered.

If anyone reading this wants WiFi enabled by default in ControlPi, please add a comment...

More info on the subject and how to enable it is here:
https://minibianpi.wordpress.com/how-to/wifi/
