### ISSUE TITLE
Improve login error message

### ISSUE THREAD

**Issue by Controlhaus** [Controlhaus/ControlPi#3]
If trying to login with an incorrect login (oops!) you get a nondescript "Something Went Wrong" message as opposed to a password/login incorrect message. This made me thing there was some sort of server error instead of realizing that I was in fact logging in with the wrong email.

**Comment by GCGarrettG** [comment]
@Controlhaus I probably wasn't clear in my report.  This applies to catch-connect not the ControlPi image
![image](https://user-images.githubusercontent.com/8333826/39591961-3d69ffd4-4eba-11e8-980d-ea2386b3654d.png)
